### ISSUE TITLE
Add generating of LoadAndDelete for go-syncmap 

### ISSUE THREAD

**Issue by denis-tingajkin** [searKing/golang#1]
Since go 1.15 for sync.Map has been added a new method that currently is not supported by go-syncmap 
https://golang.org/pkg/sync/#Map.LoadAndDelete

**Comment by denis-tingajkin** [comment]
@searKing Do you plan to fix this issue or can I provide a fix?

**Comment by searKing** [comment]
> @searKing Do you plan to fix this issue or can I provide a fix?

Thanks and Yes! LoadAndDelete of sync.Map has been added since [go1.15](https://github.com/golang/go/issues/33762), this method will be supported today.

**Comment by searKing** [comment]
- LoadAndDelete will be added from Go version 1.15 onward
- LoadAndDelete will not be generated for Go version 1.14 and earlier version
Upgrade `go-syncmap`  and have a try!

**Comment by denis-tingajkin** [comment]
@searKing thanks!
