### ISSUE TITLE
go-syncmap generates invalid file for pointer values

### ISSUE THREAD

**Issue by Bolodya1997** [searKing/golang#2]
# Issue
Running `go generate` from tests https://github.com/searKing/golang/blob/83f941a6223ab17fbd9c0023dc61ee9dc6af8604/tools/cmd/go-syncmap/testdata/nums/Nums%7Bint%2C%40string%7D.go#L15
provides such line in the generated file:
```go
var nil = func() (val *string) { return }()
```
and it affects on the test execution:
```
$ ls
Nums{int,@string}.go nums_syncmap.go
$ go run .
panic: interface conversion: interface {} is nil, not *string

goroutine 1 [running]:
main.(*Nums).Load(0xc0001062a0, 0x7f, 0x3, 0x10000c000104201)
        /Users/user/Projects/searKing/golang/tools/cmd/go-syncmap/testdata/nums/nums_syncmap.go:25 +0xbb
main.ck(0x0, 0x10bdae0, 0xc000104200, 0xc0001061b0, 0x0, 0x7f, 0x10ce097, 0x8)
        /Users/user/Projects/searKing/golang/tools/cmd/go-syncmap/testdata/nums/Nums{int,@string}.go:44 +0x8a
main.main()
        /Users/user/Projects/searKing/golang/tools/cmd/go-syncmap/testdata/nums/Nums{int,@string}.go:40 +0x44e
exit status 2
```
Removing the line fixes the issue.
# Used version
```
$ go get -u github.com/searKing/golang/tools/cmd/go-syncmap
go: golang.org/x/xerrors upgrade => v0.0.0-20200804184101-5ec99f83aff1
go: golang.org/x/tools upgrade => v0.0.0-20201102043006-b53d4cbd60a6
go: golang.org/x/mod upgrade => v0.3.0
go: github.com/searKing/golang upgrade => v0.0.82
```

# Please help us with this issue
We really need your project :)

**Comment by searKing** [comment]
> # Issue
> Running `go generate` from tests
> 
> https://github.com/searKing/golang/blob/83f941a6223ab17fbd9c0023dc61ee9dc6af8604/tools/cmd/go-syncmap/testdata/nums/Nums%7Bint%2C%40string%7D.go#L15
> 
> 
> provides such line in the generated file:
> ```go
> var nil = func() (val *string) { return }()
> ```
> 
> and it affects on the test execution:
> 
> ```
> $ ls
> Nums{int,@string}.go nums_syncmap.go
> $ go run .
> panic: interface conversion: interface {} is nil, not *string
> 
> goroutine 1 [running]:
> main.(*Nums).Load(0xc0001062a0, 0x7f, 0x3, 0x10000c000104201)
>         /Users/user/Projects/searKing/golang/tools/cmd/go-syncmap/testdata/nums/nums_syncmap.go:25 +0xbb
> main.ck(0x0, 0x10bdae0, 0xc000104200, 0xc0001061b0, 0x0, 0x7f, 0x10ce097, 0x8)
>         /Users/user/Projects/searKing/golang/tools/cmd/go-syncmap/testdata/nums/Nums{int,@string}.go:44 +0x8a
> main.main()
>         /Users/user/Projects/searKing/golang/tools/cmd/go-syncmap/testdata/nums/Nums{int,@string}.go:40 +0x44e
> exit status 2
> ```
> 
> Removing the line fixes the issue.
> 
> # Used version
> ```
> $ go get -u github.com/searKing/golang/tools/cmd/go-syncmap
> go: golang.org/x/xerrors upgrade => v0.0.0-20200804184101-5ec99f83aff1
> go: golang.org/x/tools upgrade => v0.0.0-20201102043006-b53d4cbd60a6
> go: golang.org/x/mod upgrade => v0.3.0
> go: github.com/searKing/golang upgrade => v0.0.82
> ```
> 
> # Please help us with this issue
> We really need your project :)

My mistake! This bug is introduced by I have refactored this code by template in the morning, it has been fixed now.
All the tests have been passed under examples.
Sorry for the inconvenience.
