### ISSUE TITLE
go install invokes Replace Directives error.

### ISSUE THREAD

**Issue by aellisv** [searKing/golang#20]
I am getting the 'replace directives' error when attempting to install the tools/go-enum module:

```
$ go install github.com/searKing/golang/tools/go-enum@latest
go: github.com/searKing/golang/tools/go-enum@v1.2.112 (in github.com/searKing/golang/tools/go-enum@v1.2.112):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.

$  go version
go version go1.21.4 darwin/arm64
$ date
Tue Jan  2 23:57:40 UTC 2024
```

Running on MacOS 13.6.2 (22G320).

**Comment by alhails** [comment]
Workaround in the meantime...
`go install github.com/searKing/golang/tools/go-enum@v1.2.97`

**Comment by searKing** [comment]
+ It has been fixed now, install the latest version `go install github.com/searKing/golang/tools/go-enum@v1.2.113`.
https://github.com/golang/go/issues/44840

**Comment by searKing** [comment]
+ This currently fails on go >= 1.16 due to replace directives. See: https://github.com/golang/go/issues/44840
+ It has been fixed now with `replace` removed, install the latest version `go install github.com/searKing/golang/tools/go-enum@v1.2.113`.
