### ISSUE TITLE
slog &  documentation

### ISSUE THREAD

**Issue by sysmat** [searKing/golang#23]
- Do you have any beginners documentation or some example how to use your package.
-  I'm trying [NewRotateTextHandler](https://pkg.go.dev/github.com/searKing/golang/go/log/slog#NewRotateTextHandler) but can not find how configure [RotateOption](https://pkg.go.dev/github.com/searKing/golang/go/log/slog#RotateOption)
- and what is path, relative or absolute

- basic try it throws error(using go version go1.21.6 windows/amd64)
```
# github.com/searKing/golang/go/os
..\..\..\..\go\pkg\mod\github.com\sear!king\golang\go@v1.2.114\os\clean.go:122:24: cannot use avail (variable of type uint64) as int64 value in argument to quora.ExceedBytes
..\..\..\..\go\pkg\mod\github.com\sear!king\golang\go@v1.2.114\os\clean.go:122:31: cannot use total (variable of type uint64) as int64 value in argument to quora.ExceedBytes
..\..\..\..\go\pkg\mod\github.com\sear!king\golang\go@v1.2.114\os\clean.go:125:25: cannot use inodes - inodesFree (value of type uint64) as int64 value in argument to quora.ExceedInodes
..\..\..\..\go\pkg\mod\github.com\sear!king\golang\go@v1.2.114\os\clean.go:125:44: cannot use inodes (variable of type uint64) as int64 value in argument to quora.ExceedInodes
..\..\..\..\go\pkg\mod\github.com\sear!king\golang\go@v1.2.114\os\disk_windows.go:83:73: cannot use lpFreeBytesAvailable (variable of type int64) as uint64 value in return statement
```

**Comment by searKing** [comment]
+ Here is an brief example of [NewRotateTextHandler](https://pkg.go.dev/github.com/searKing/golang/go@v1.2.115/log/slog#example-NewRotateTextHandler)
+ [RotateOption](https://pkg.go.dev/github.com/searKing/golang/go/log/slog#RotateOption) follows **Golang Functional Options Pattern**, as introduced in [Rob Pike. Self-referential functions and the design of options. Jan 24, 2014.](https://commandcenter.blogspot.com/2014/01/self-referential-functions-and-design.html)
```go
package main

import (
	"log/slog"
	"path/filepath"
	"time"

	slog_ "github.com/searKing/golang/go/log/slog"
)

func main() {
	replace := func(groups []string, a slog.Attr) slog.Attr {
		// Remove the directory from the source's filename.
		if a.Key == slog.SourceKey {
			source := a.Value.Any().(*slog.Source)
			source.File = filepath.Base(source.File)
		}
		return a
	}
	handler, err := slog_.NewRotateTextHandler("/tmp/slog/example.log",
		&slog.HandlerOptions{AddSource: true, ReplaceAttr: replace}, // If opts is nil, the default options are used.
		slog_.WithRotateRotateInterval(time.Hour),
		slog_.WithRotateMaxCount(3),
		slog_.WithRotateMaxAge(24*time.Hour),
		// Below is default options.
		// WithRotateFilePathRotateStrftime(".%Y%m%d%H%M%S.log"), // time layout in strftime format to format rotate file.
		// WithRotateFilePathRotateLayout(".20060102150405.log"), // time layout in golang format to format rotate file.
		// WithRotateFileLinkPath(filepath.Base(path) + ".log"), // the symbolic link name that gets linked to the current file name being used.
	)
	if err != nil {
		panic("failed to create rotate text handler:" + err.Error())
	}
	slog.SetDefault(slog.New(handler))
	slog.Info("rotate text message")

	// example.log -> /tmp/slog/example.log
	// /tmp/slog/example.20240202170000.log
	// /tmp/slog/example.20240202180000.log
	// ...
}
```
+ path can be relative path or absolute path. If path is empty, the default os.Stdout are used. 
+ it's not tested on windows before, please update to **github.com/searKing/golang/go v1.2.115** and have a try. 
+ [advance example for register slog as the backend handler for logrus](https://github.com/searKing/golang/blob/master/third_party/github.com/sirupsen/logrus/logrus.factory.slog.go#L20)

**Comment by searKing** [comment]
Now **GitHub Workflow** runs `go test` on [macos-latest, ubuntu-latest, windows-latest].
[<img width="640" alt="image" src="https://github.com/searKing/golang/assets/4208726/9e07e3d0-8bf4-45ed-9d2f-b18296bdad1d">](https://github.com/searKing/golang/actions/runs/7764555457)
