### ISSUE TITLE
Tags sorting is constantly changing

### ISSUE THREAD

**Issue by epicbytes** [searKing/golang#32]
hi, I found a problem where re-generating *.proto files causes the tags added through your module to be overwritten in chaotic sorting. The problem is that after reflection, the tags are sorted into a map; after they are rendered into a file, the tag values are overwritten without taking into account sorting.

https://github.com/searKing/golang/blob/d25903d81f4dde8936db12f1b4a0b48b243cf18b/tools/protoc-gen-go-tag/ast/parse_and_rewrite.go#L23

The problem is critical and litters commits.

<img width="792" alt="image" src="https://github.com/searKing/golang/assets/5072946/44d02e95-3a7a-483b-b55e-851b5b80d2a9">

**Comment by searKing** [comment]
+ the order rule of struct tags is: `protobuf`, `json`, other tags in original order.
```protobuf
message Http{
  string test_order_tag_form_v8n = 10[(google.protobuf.field_tag) = {struct_tag: 'form:"currency_uso,omitempty" v8n:"required"'}];
  string test_order_tag_v8n_form = 11[(google.protobuf.field_tag) = {struct_tag: 'v8n:"required" form:"currency_uso,omitempty"'}];
}
```

```go
type Http struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	TestOrderTagFormV8N string    `protobuf:"bytes,10,opt,name=test_order_tag_form_v8n,json=testOrderTagFormV8n,proto3" json:"test_order_tag_form_v8n,omitempty" form:"currency_uso,omitempty" v8n:"required"`
	TestOrderTagV8NForm string    `protobuf:"bytes,11,opt,name=test_order_tag_v8n_form,json=testOrderTagV8nForm,proto3" json:"test_order_tag_v8n_form,omitempty" v8n:"required" form:"currency_uso,omitempty"`
}
```
