### ISSUE TITLE
go get github.com/searKing/golang/tools/cmd/protoc-gen-go-tag fails since this morning

### ISSUE THREAD

**Issue by hurdadurda** [searKing/golang#6]
go get github.com/searKing/golang/tools/cmd/protoc-gen-go-tag: ambiguous import: found package github.com/searKing/golang/tools/cmd/protoc-gen-go-tag in multiple modules:
        github.com/searKing/golang v1.0.101 (/go/pkg/mod/github.com/sear!king/golang@v1.0.101/tools/cmd/protoc-gen-go-tag)
        github.com/searKing/golang/tools/cmd/protoc-gen-go-tag v0.0.0-20210105170217-17eed9a84a13 (/go/pkg/mod/github.com/sear!king/golang/tools/cmd/protoc-gen-go-tag@v0.0.0-20210105170217-17eed9a84a13)

Looks like when we install your package we end up with it in two places under GOPATH (in my case /go:

/go/pkg/mod/github.com/sear!king/golang@v1.0.101/tools/cmd/protoc-gen-go-tag
/go/pkg/mod/github.com/sear!king/golang/tools/cmd/protoc-gen-go-tag@v0.0.0-20210105170217-17eed9a84a13

I am new at Go and not sure why the go get ends up with two copies of the code but that breaks the build of the protoc-gen-go-tag executable somehow.

Just noticed that this fails: 
go get -u github.com/searKing/golang/tools/cmd/protoc-gen-go-tag 

go get -u github.com/searKing/golang/tools/cmd/protoc-gen-go-tag 
go: google.golang.org/protobuf upgrade => v1.25.0
go: github.com/golang/protobuf upgrade => v1.4.3
go: github.com/searKing/golang upgrade => v1.0.101
go get github.com/searKing/golang/tools/cmd/protoc-gen-go-tag: ambiguous import: found package github.com/searKing/golang/tools/cmd/protoc-gen-go-tag in multiple modules:
        github.com/searKing/golang v1.0.101 (~/.go/pkg/mod/github.com/sear!king/golang@v1.0.101/tools/cmd/protoc-gen-go-tag)
        github.com/searKing/golang/tools/cmd/protoc-gen-go-tag v0.0.0-20210105170217-17eed9a84a13 (~/.go/pkg/mod/github.com/sear!king/golang/tools/cmd/protoc-gen-go-tag@v0.0.0-20210105170217-17eed9a84a13)

While this works fine:

go get github.com/searKing/golang/tools/cmd/protoc-gen-go-tag

Note the missing -u .

**Comment by searKing** [comment]
### Reason
+ It's caused by git history rewrite `git filter-branch`, all go.mod&go.sum has been removed except which were under `github.com/searKing/golang`
+ tools will follow git repo's tag now, as `v1.0.101`, not `v0.0.0-20210105170217-17eed9a84a13`

### Solution
+ just remove the entire module download cache by 
`go clean -modcache`
+ or remove selected download cache by 
`rm "$(go env GOMODCACHE)/github.com/sear!king/golang/tools/cmd/protoc-gen-go-tag@"*`

**Comment by hurdadurda** [comment]
Speedy!!!

I've tried that before and it didn't work:

$ go clean -modcache
$ go get -u github.com/searKing/golang/tools/cmd/protoc-gen-go-tag
go: downloading github.com/searKing/golang/tools/cmd/protoc-gen-go-tag v0.0.0-20210105170217-17eed9a84a13
go: downloading github.com/searKing/golang v0.0.95
go: downloading google.golang.org/protobuf v1.25.0
go: downloading github.com/golang/protobuf v1.4.3
go: github.com/golang/protobuf upgrade => v1.4.3
go: google.golang.org/protobuf upgrade => v1.25.0
go: github.com/searKing/golang upgrade => v1.0.101
go: downloading github.com/searKing/golang v1.0.101
go get github.com/searKing/golang/tools/cmd/protoc-gen-go-tag: ambiguous import: found package github.com/searKing/golang/tools/cmd/protoc-gen-go-tag in multiple modules:
        github.com/searKing/golang v1.0.101 (/Users/andreigeorgescu/.go/pkg/mod/github.com/sear!king/golang@v1.0.101/tools/cmd/protoc-gen-go-tag)
        github.com/searKing/golang/tools/cmd/protoc-gen-go-tag v0.0.0-20210105170217-17eed9a84a13 (/Users/andreigeorgescu/.go/pkg/mod/github.com/sear!king/golang/tools/cmd/protoc-gen-go-tag@v0.0.0-20210105170217-17eed9a84a13)

// Also:
$ ls ~/.go/pkg/mod/github.com/sear\!king/
golang          golang@v0.0.95  golang@v1.0.101

So the 'go clean -modcache' is not cleaning up much.

Removing all the folders named "sear\!king" under folder $(go env GOPATH) doesn't solve the issue either.

Also my build runs in a fresh docker instance based on golang:latest so it is always clean when I run:
go get -u github.com/searKing/golang/tools/cmd/protoc-gen-go-tag 
and still returns the error.

The difference is in something related to the -u switch used for the go get command.

**Comment by searKing** [comment]
It seems like `v0.0.0-20210105170217-17eed9a84a13` is remove in github.com but buffered in you docker instance.
![image](https://user-images.githubusercontent.com/4208726/103854719-20ef7500-50ec-11eb-9d58-1a32af2520eb.png)

Could you please try to install by specific version as codes below?
```bash
GO111MODULE=on go get -u github.com/searKing/golang/tools/cmd/protoc-gen-go-tag@v1.0.101
```

**Comment by searKing** [comment]
go.mod and go.sum have been restored for backward compatibility since v0.0.102.
So `go get -u github.com/searKing/golang/tools/cmd/protoc-gen-go-tag` will not fail now.

**Comment by searKing** [comment]
for old versions cannot be removed from go proxy cache, https://github.com/golang/go/issues/46440
```bash
# install a base version, such as v1.0.175
go get -u github.com/searKing/golang/tools/cmd/protoc-gen-go-tag@v1.0.175
# update to latest version of this tool
go get -u github.com/searKing/golang/tools/cmd/protoc-gen-go-tag
```
